name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup environment
        run: make setup
      - name: Run checks
        run: |
          source .venv/bin/activate
          python -m mypy src
          python -m pytest tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
